export const songs = [
    {
      id: 1,
      title: "Kodikayarana Pooramai",
      lengthInSeconds: 294,
      playing: 1357890,
      time: "02:23",
      album: "Aadu",
      artist: "Shaan Rahman",
      cover: "https://c.saavncdn.com/186/Aadu-2-Malayalam-2018-20231130070921-500x500.jpg",
      song: "/music/aadu1.mov",
    },
    {
      id: 2,
      title: "Ente Mavum Pooth",
      lengthInSeconds: 357,
      playing: 1543201,
      time: "05:57",
      album: "Adi Kapyare Koottamani",
      artist: "Vineeth & team",
      cover: "https://c.saavncdn.com/328/Adi-Kapyare-Koottamani-Malayalam-2015-500x500.jpg",
      song: "/music/emp.mov",
    },
    {
      id: 5,
      title: "Ennilerinju thudnagi",
      lengthInSeconds: 248,
      playing: 1012345,
      time: "04:08",
      album: "Jacobinte Swargarajyam",
      artist: "Vineeth, Shaan Rahman",
      cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShnYUeUFp-jYYqZytApnJvD4PCa3T0iW0JWg&s",
      song: "/music/js.mov",
    },
    {
      id: 6,
      title: "Pakalin Vaathil",
      lengthInSeconds: 273,
      playing: 987654,
      time: "04:33",
      album: "parava",
      artist: "Sreenath Bhasi ",
      cover: "https://i.scdn.co/image/ab67616d0000b2735d14e857caf68271fbf5d3e0",
      song: "/music/pvt.mov",
    },
    // {
    //   id: 7,
    //   title: "Man in the Mirror",
    //   lengthInSeconds: 319,
    //   playing: 856789,
    //   time: "05:19",
    //   album: "Bad",
    //   artist: "Michael Jackson",
    //   cover: "https://i1.sndcdn.com/artworks-000206393695-gtqwch-t500x500.jpg",
    //   song: "/music/bad.mov",
    // },
    // {
    //   id: 8,
    //   title: "Remember the Time",
    //   lengthInSeconds: 239,
    //   playing: 935421,
    //   time: "03:59",
    //   album: "Dangerous",
    //   artist: "Michael Jackson",
    //   cover: "https://i1.sndcdn.com/artworks-Jk9sOGgsEzpO5wBf-kynGZw-t500x500.jpg",
    //   song: "/music/remember-the-time.mov",
    // },
    // {
    //   id: 9,
    //   title: "Earth Song",
    //   lengthInSeconds: 366,
    //   playing: 965432,
    //   time: "06:06",
    //   album: "HIStory",
    //   artist: "Michael Jackson",
    //   cover: "https://i1.sndcdn.com/artworks-krOtBM00N6DmfhTX-qwsklg-t500x500.jpg",
    //   song: "/music/earth.mov",
    // },
  ];